### ISSUE TITLE
It's possible to redo a release which will integrate fix needed?

### ISSUE THREAD

**Issue by dinosaure** [sg2342/mirage-block-ccm#27]
Currently, `mirage-block-ccm.1.0.1` is unavailable for few reasons (specially `io-page`) on recent versions of OCaml (4.14.0) and it will be nice to make a release. I see that a release is pending into `ocaml/opam-repository` but few fixes are needed to be able to merge then this package. Can you redo the release to unlock the ability to use `mirage-block-ccm`?

I really would like to definitely integrate `mirage-block-ccm` as a MirageOS device into the `mirage` tool. By this way, it will be easy to use your library for a MirageOS user such as, into the `config.ml`, he/she will be able to:
```ocaml
let aes_ccm_key =
  let doc = Key.Arg.info [ "aes-ccm-key" ] in
  Key.(create "aes_ccm_key" Arg.(required string doc))

let block = block_of_file "disk"
let ccm = ccm aes_ccm_key block
let () = unikernel $ ccm
```

**Comment by dinosaure** [comment]
I made #28 which will be nice to integrate to the release too. By this way, the user is able to craft an encrypted image just via the installation of the distribution.

**Comment by hannesm** [comment]
done in https://github.com/ocaml/opam-repository/pull/22364
